#!/bin/sh

# check priviledges
if [ $UID != "0" ]; then
  
  echo -e "Run with sudo priviledges\n"
  exit

else
  
  # install scapy, dependencies
  sudo apt install tcpdump graphviz imagemagick python-gnuplot python-crypto python-pyx
  pip install scapy

  # instal python-NetfilterQueue
  sudo apt install build-essential python-dev libnetfilter-queue-dev
  cd ~/Downloads
  if [ ! -d $python-netfilterqueue ]; then
    git clone https://github.com/fqrouter/python-netfilterqueue.git
  fi
    cd python-netfilterqueue
    python setup.py install
fi




